export const Data = [
    {
        id:0,
        brand:"Allensolly",
        size: 42,
        color:"blue",
        price: 1000,
        image:"https://imagescdn.allensolly.com/img/app/product/8/891433-10800081.jpg?auto=format&w=390",
        type:"shirt",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:1,
        brand:"Allensolly",
        size: 42,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39625469-12886978.jpg?auto=format&w=390",
        type:"shirt",
        product:"old",
        season:"snow",
        gender:"M",
        fit:"Regular Fit"
    }
    ,
    {
        id:2,
        brand:"Allensolly",
        size: 40,
        color:"brown",
        price: 1800,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39630670-13070913.jpg?auto=format&w=390",
        type:"shirt",
        product:"new",
        season:"rain",
        gender:"M",
        fit:"Slim Fit"
    },
    {
        id:3,
        brand:"Allensolly",
        size: 46,
        color:"grey",
        price: 2000,
        image:"https://imagescdn.allensolly.com/img/app/product/9/951848-12285671.jpg?auto=format&w=390",
        type:"shirt",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:4,
        brand:"Allensolly",
        size: 42,
        color:"green",
        price: 2500,
        image:"https://imagescdn.allensolly.com/img/app/product/8/893114-11054682.jpg?auto=format&w=390",
        type:"shirt",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Slim Fit"
    },
    {
        id:5,
        brand:"Allensolly",
        size: 40,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39621921-12718863.jpg?auto=format&w=390",
        type:"shirt",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:6,
        brand:"Allensolly",
        size: 32,
        color:"black",
        price: 1000,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678892-13784717.jpg?auto=format&w=390",
        type:"pant",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:7,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1200,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678928-13785698.jpg?auto=format&w=390",
        type:"pant",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Angle Fit"
    },
    {
        id:8,
        brand:"Allensolly",
        size: 32,
        color:"grey",
        price: 1000,
        image:"https://imagescdn.allensolly.com/img/app/product/9/966168-12633928.jpg?auto=format&w=390",
        type:"pant",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:9,
        brand:"Allensolly",
        size: 34,
        color:"black",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/7/749755-8473472.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Regular Fit"
    },
    {
        id:10,
        brand:"Allensolly",
        size: 30,
        color:"black",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/7/749755-8473472.jpg?auto=format&w=390",
        type:"pant",
        product:"new",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:11,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },{
        id:12,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:13,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:14,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:15,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:16,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:17,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"snow",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:18,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:19,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    {
        id:20,
        brand:"Allensolly",
        size: 34,
        color:"white",
        price: 1500,
        image:"https://imagescdn.allensolly.com/img/app/product/3/39678332-13770747.jpg?auto=format&w=390",
        type:"pant",
        product:"old",
        season:"summer",
        gender:"M",
        fit:"Angle fit"
    },
    
];